# Generated by Django 5.0.7 on 2024-09-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fundName', models.CharField(blank=True, max_length=1500, null=True, unique=True)),
                ('hideStatus', models.BooleanField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='navmodel',
            new_name='apis_navmod_navFund_6fbd43_idx',
            old_name='apis_navmod_navFund_e092a5_idx',
        ),
        migrations.RemoveField(
            model_name='navmodel',
            name='navAmcName',
        ),
        migrations.AddField(
            model_name='fundmodel',
            name='fundAmcName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundAmcName', to='apis.amcentrymodel'),
        ),
        migrations.AlterField(
            model_name='navmodel',
            name='navFundName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navFundName', to='apis.fundmodel'),
        ),
    ]
