# Generated by Django 5.0.7 on 2024-09-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_fundmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundmodel',
            name='hideStatus',
            field=models.IntegerField(default=0),
        ),
    ]
