# Generated by Django 5.0.7 on 2024-09-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_fundmodel_hidestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundmodel',
            name='schemeCode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fundmodel',
            name='fundAmcName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundAmcName', to='apis.amcentrymodel'),
        ),
    ]
