# Generated by Django 5.0.7 on 2024-09-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_fundmodel_schemecode_alter_fundmodel_fundamcname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundmodel',
            name='fundName',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
