# Generated by Django 5.0.7 on 2024-09-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_fundmodel_fundname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentrymodel',
            name='dailyEntryClientMobileNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyEntryClientMobileNumber', to='apis.clientmodel'),
        ),
        migrations.AlterField(
            model_name='dailyentrymodel',
            name='dailyEntryClientPanNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyEntryClientPanNumber', to='apis.clientmodel'),
        ),
    ]
