# Generated by Django 5.0.7 on 2024-09-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_dailyentrymodel_dailyentryclientmobilenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentrymodel',
            name='dailyEntryFundName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyEntryFundName', to='apis.fundmodel'),
        ),
    ]
