# Generated by Django 5.0.7 on 2024-09-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_remove_issuemodel_issuedailyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='issueDailyEntry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issueDailyEntry', to='apis.dailyentrymodel'),
        ),
    ]
