# Generated by Django 5.0.7 on 2024-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_couriermodel_courierclientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnentrymodel',
            name='arnNumber',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
