# Generated by Django 5.0.7 on 2024-09-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_arnentrymodel_arnnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileTypeName', models.CharField(blank=True, max_length=200, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
