# Generated by Django 5.0.7 on 2024-09-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_filetypemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmodel',
            name='marketingType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketingType', to='apis.filetypemodel'),
        ),
    ]
