# Generated by Django 5.0.7 on 2024-09-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_countrymodel_statemodel_statecountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pinCode', models.CharField(blank=True, max_length=6, null=True)),
                ('pinCodeCity', models.CharField(blank=True, max_length=250, null=True)),
                ('hideStatus', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('pinCodeState', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinCodeState', to='apis.statemodel')),
            ],
        ),
    ]
