# Generated by Django 5.0.7 on 2024-09-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_pincodemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincodemodel',
            name='pinCodeCity',
        ),
    ]
