# Generated by Django 5.0.7 on 2024-09-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_remove_pincodemodel_pincodecity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PincodeModel',
        ),
    ]
