# Generated by Django 5.0.7 on 2024-09-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_delete_pincodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='arnentrymodel',
            name='arnCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arnCountryCode', to='apis.countrymodel'),
        ),
        migrations.AddField(
            model_name='dailyentrymodel',
            name='dailyEntryClientCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyEntryClientCountryCode', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='arnentrymodel',
            name='arnCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arnCountry', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='arnentrymodel',
            name='arnMobile',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
