# Generated by Django 5.0.7 on 2024-09-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_arnentrymodel_arncountrycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriermodel',
            name='courierCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courierCountryCode', to='apis.countrymodel'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='employeeCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeCountryCode', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='couriermodel',
            name='courierMobileNumber',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='employeePhone',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
