# Generated by Django 5.0.7 on 2024-10-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_couriermodel_couriercountrycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='clientAlternatePhoneCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientAlternatePhoneCountryCode', to='apis.countrymodel'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='clientPhoneCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientPhoneCountryCode', to='apis.countrymodel'),
        ),
        migrations.AddField(
            model_name='clientofficeaddressmodel',
            name='clientOfficeCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientOfficeCountryCode', to='apis.countrymodel'),
        ),
        migrations.AddField(
            model_name='clientoverseasaddressmodel',
            name='clientOverseasCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientOverseasCountryCode', to='apis.countrymodel'),
        ),
        migrations.AddField(
            model_name='clientpermanentaddressmodel',
            name='clientPermanentCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientPermanentCountryCode', to='apis.countrymodel'),
        ),
        migrations.AddField(
            model_name='clientpresentaddressmodel',
            name='clientPresentCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientPresentCountryCode', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='clientCountryOfBirth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientCountryOfBirth', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='clientofficeaddressmodel',
            name='clientOfficeCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientOfficeCountry', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='clientoverseasaddressmodel',
            name='clientOverseasCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientOverseasCountry', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='clientpermanentaddressmodel',
            name='clientPermanentCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientPermanentCountry', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='clientpresentaddressmodel',
            name='clientPresentCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientPresentCountry', to='apis.countrymodel'),
        ),
        migrations.AlterField(
            model_name='clienttaxmodel',
            name='clientTaxCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientTaxCountry', to='apis.countrymodel'),
        ),
    ]
