# Generated by Django 5.0.7 on 2024-10-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_clientmodel_clientalternatephonecountrycode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentrymodel',
            name='dailyEntryClientCountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyEntryClientCountryCode', to='apis.clientmodel'),
        ),
    ]
