# Generated by Django 5.0.7 on 2024-10-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_alter_dailyentrymodel_dailyentryclientcountrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcentrymodel',
            name='amcCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amcCountry', to='apis.countrymodel'),
        ),
    ]
