# Generated by Django 5.0.7 on 2024-10-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0028_activitylog_previous_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriermodel',
            name='courierEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
